stages:
  - build
  - test
  - deploy

variables: 
  DOCKER_IMAGE: 'my_app'

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE python -m unittest discover

deploy:
  stage: deploy
  script:
    - docker run -d -p 5000:5000 $DOCKER_IMAGE